## Memoria
vm_memory_high_watermark.relative = 0.7

## Espacio mínimo libre en disco
disk_free_limit.absolute = 2GB

## Management
management.tcp.port = 15672

## Listener AMQP
listeners.tcp.default = 5672

## Log
log.console = true

## Guest remoto (opcional)
loopback_users = none